# These are supported funding model platforms by GitHub
github: huynhnhanquoc          # GitHub Sponsors username
patreon: huynhnhanquoc         # Optional
ko_fi: huynhnhanquoc           # Optional
buy_me_a_coffee: huynhnhanquoc # Optional
custom:
  - https://www.paypal.me/huynhnhanquoc
